### PR TITLE
be able to move microservices #6

### PR DESCRIPTION
**Pull request by simbo1905**
Adds a fact check to conditionally install based on `sb_hosts`.

### CODE REVIEW

**Comment by orachide** [comment]
Hello,

I just read your PR and i thing for a good separation of concern, an Ansible role should not handle or have any knowledge about hosts or groups.

You should be able to reach the same goal by setting the `sb_app_state ` variable at the playbook level and not in the role.

If you use this role i assume your first need is to install a Spring boot App that's why `sb_app_state ` is set to `true` by default.

An exemple playbook could look like this (based on the the exemple in the README.md)

```yaml
- name: Converge
  hosts: all
  set_fact: # This set_fact block should be ok for your need ******************
    sb_app_state="{% if ansible_hostname in groups.springboot_hosts %}present{% else %}absent{% endif %}"
  vars:
    # add common vars for all deployments up here
    sb_java_package: java-1.8.0-openjdk
    sb_app_as_a_service: true
    sb_app_extension: jar
    sb_applications_root_folder: /opt/applis
    sb_app_group_id: "org.springframework.samples.service.service"
  roles:
    - {
      role: "ansible-role-springboot",
      sb_app_name: "microservices-registration",
      sb_app_artifact_id: "my-frontend",
      sb_app_version: "2.0.0.RELEASE",
      sb_app_run_args: '"registration 8082"',
      sb_app_healthcheck_urls: [
        "http://localhost:8082/actuator/health"
      ]
    }
    - {
      role: "ansible-role-springboot",
      sb_app_name: "microservices-web",
      sb_app_artifact_id: "my-backend",
      sb_app_version: "2.0.0.RELEASE",
      sb_app_run_args: '"web 8083"',
      sb_app_healthcheck_urls: [
        "http://localhost:8083/actuator/health"
      ]
    }

```
`springboot_hosts` is an existing group in your inventory.

What do you think about this solution?

**Comment by simbo1905** [comment]
You example above seems to place all of microservices on the host depending on whether the host is in a single? We want fine grained placement per microservice and host. 

For example we might have five large VMs. Some microservices we run on all five hosts. Some low volume ones may only run on two hosts for HA. Each role definition in the playbook defines the details of one microservice. So to define which hosts the microservice runs on is defined at the level of invoking the role. 

I hear your reasoning that it seems like “role knows hosts” this isn’t how I think of it. The config is at a “per microservice level” in the playbook. (It’s not defined in the roles subfolder so it isn’t defined at role level.) 

That is the only way I can see to get per microservice and per host with the list of which microservice is where in “one place”. If we can factor that out into a separate vars file rather than editing the main playbook the perhaps that might be cleaner?

**Comment by orachide** [comment]
OK let's say we have the following inventory file (using your last example)

```yaml
# hosts file
[microservices-vm] # large 5 vm you were talking about
vm01
vm02
vm03
vm04
vm05

[low-volumes-microservices] # group of vm where low volume microservices will be installed
vm04
vm05
```
And the playbook

```yaml
# Playbook file

- name: Install microservices
  hosts: microservices-vm
  vars:
    # add common vars for all deployments up here
    sb_java_package: java-1.8.0-openjdk
    sb_app_as_a_service: true
    sb_app_extension: jar
    sb_applications_root_folder: /opt/applis
    sb_app_group_id: "org.springframework.samples.service.service"
  roles:
    - {
      role: "ansible-role-springboot",
      sb_app_name: "microservices-registration",
      sb_app_artifact_id: "my-frontend",
      sb_app_version: "2.0.0.RELEASE",
      sb_app_run_args: '"registration 8082"',
      sb_app_healthcheck_urls: [
        "http://localhost:8082/actuator/health"
      ],
      sb_app_state: "{% if ansible_hostname in groups['low-volumes-microservices'] %}present{% else %}absent{% endif %}"
    }
    - {
      role: "ansible-role-springboot",
      sb_app_name: "microservices-web",
      sb_app_artifact_id: "my-backend",
      sb_app_version: "2.0.0.RELEASE",
      sb_app_run_args: '"web 8083"',
      sb_app_healthcheck_urls: [
        "http://localhost:8083/actuator/health"
      ]
    }
```
Is that what you want to achieve? In this example the microservice  `microservices-registration` will be installed only on `vm04` and `vm05` (inventory group `low-volumes-microservices`) right?

I still think that there is no need to change the role to get your scenario working.

Let me know if this is not enough for you. Thanks

**Comment by simbo1905** [comment]
Sorry I had misunderstood you. Yes that looks like it should work. Your approach has the advantage that people comprehend inventories. The j2 logic is really ugly though and I think it will be unapproachable to the many teams we have. I would understand it if you kept things they way they are.

**Comment by orachide** [comment]
Actually there are many ways to avoid using the Jinja expression.
As your need is per host (and per micro service deployment) you could use  `host_vars` to define if `microservices-registration` should be present or not on each node.

Your `host_vars` directory structure will look like this
```
root_folder
    |─ host_vars
              |─ vm01
              |─ vm04
```

In the file `root_folder/host_vars/vm01`
```yaml
registration_service_state: "absent" # or present depending on your need
```
In the file `root_folder/host_vars/vm04`
```yaml
web_service_state: "present" # or absent depending on your need
```

And the last update in your playbook

```yaml
# Playbook file

- name: Install microservices
  hosts: microservices-vm
  vars:
    # add common vars for all deployments up here
    sb_java_package: java-1.8.0-openjdk
    sb_app_as_a_service: true
    sb_app_extension: jar
    sb_applications_root_folder: /opt/applis
    sb_app_group_id: "org.springframework.samples.service.service"
  roles:
    - {
      role: "ansible-role-springboot",
      sb_app_name: "microservices-registration",
      sb_app_artifact_id: "my-frontend",
      sb_app_version: "2.0.0.RELEASE",
      sb_app_run_args: '"registration 8082"',
      sb_app_healthcheck_urls: [
        "http://localhost:8082/actuator/health"
      ],
      sb_app_state: "{{ registration_service_state }}"
    }
    - {
      role: "ansible-role-springboot",
      sb_app_name: "microservices-web",
      sb_app_artifact_id: "my-backend",
      sb_app_version: "2.0.0.RELEASE",
      sb_app_run_args: '"web 8083"',
      sb_app_healthcheck_urls: [
        "http://localhost:8083/actuator/health"
      ]
    }
```
As your concern is an inventory configuration it should be kept in the inventory and ansible allow this using `group_vars` or `host_vars`.

I'll close this and thanks for your contribution :)

**Comment by simbo1905** [comment]
Thanks for the explanation. I have learnt a lot from looking at the code and your thoughtful comments. 

I am a little shy about using host vars. For example, to see where a microservices is installed you need to look at all the host vars which is cognitive overhead. In general, they seem like a "cattle not sheep" concept but I will keep an open mind. 

Group vars sounds like a good idea. I can create a group per microservice so can see where a microservice is defined in one place. It is slightly tedious to define inventory groups on Tower but I will try it out when I get some time. Thanks again!

**Pull request closed without merging**
